<div class=\"alert alert-block alert-info\">
<center>ESTATÍSTICA APLICADA</center>
<center>LISTA 1</center>
<center>ALUNO: ARTHUR MAURICIO</center>
</div>

### Questão 1

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.22.2


### Questão 2

- Broadcasting: O broadcasting é a forma que o numpy usa para tratar operações aritimétricas com vétores (ou não vétores) de tamanhos distintos. Por exemplo, multiplicar um vetor de tamanho 10 de números reais com um valor X irá multiplicar cada item do vetor por esse x.
- Vetorização: A vetorização é a forma que o numpy usa de tornar operações com listas mais rápidas do que usando a sintaxe usual de listas do python (for loops etc). Dessa forma é bem mais fácil trabalhar com matrizes e vetores utilizando o ndarray

### Questão 3

- Dicionario: É um dicionario chave:valor, onde suas chaves podem ser de qualquer tipo e seu valor também. A indexação é feita comparando o valor com as chaves do dicionário. A sintáxe é a mesma das listas

In [4]:
a = dict()
a["foo"] = "bar"
a[False] = True
a[2] = [1,2,3]
print(a)
print(a[False])

{'foo': 'bar', False: True, 2: [1, 2, 3]}
True


- Lista: Estrutura básica de coleção do Python, nela podemos guardar um conjunto de dados de qualquer tipo (inclusive dados de tipos diferentes numa mesma lista). É indexada por posições da seguinte forma: lista[0]

In [5]:
lista = [1,2,3,"4",5.123]
print(lista)
print(lista[2])

[1, 2, 3, '4', 5.123]
3


- Array Numpy: o método np.array() cria um objeto Array, que funciona básicamente como uma lista comum porém com diversos métodos e facilidades para trabalhar com grandes conjuntos de dados. O Array Numpy só pode ter um tipo de dados e tem métodos como sum(), std() etc.

In [6]:
np_arr = np.array([1,2,3,4,5.213])
print(np_arr)
print(np_arr.sum())

[1.    2.    3.    4.    5.213]
15.213000000000001


### Questão 4

In [7]:
base = [[j for j in range((i-1)*5 + 1, i*5 + 1)] for i in range(1,4)]
print(base)
np.array(base).transpose()

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]


array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

### Questão 5

In [8]:
## a
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [9]:
## b
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [10]:
## c
c = np.zeros((3,3))
np.fill_diagonal(c,[1,2,3])
c

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

### Questão 6

In [11]:
l = [-2,4.,'7',9]
np.array(l)

array(['-2', '4.0', '7', '9'], dtype='<U32')

Essa mudança ocorre pois o numpy busca por um tipo em comum para todos os items no vetor, já que ele permite apenas um tipo de dado em sua especificação. Nesse caso o tipo de dado em que todos os items podem ser transformados é uma string.   

Porém, se mudarmos o '7' para inteiro, o tipo de dados em comum para que todos podem ser transformados é float (por conta do -2.4)
.

In [12]:
np.array([-2,4.,7,9])

array([-2.,  4.,  7.,  9.])

### Questão 7

In [13]:
A = np.arange(10,49)
B = np.arange(1,39)
C = np.arange(10,20)

In [14]:
## a
A + B

ValueError: operands could not be broadcast together with shapes (39,) (38,) 

In [ ]:
A * B

In [ ]:
A + C

In [ ]:
B*C

As operações dão erro pois o tamanho dos arrays são incompatíveis para o broadcast.

Para dar certo, precisariamos normalizar os três arrays e deixalos com o mesmo tamanho. Vamos deixa-los com tamanho 49.

In [ ]:
A.resize(49)
B.resize(49)
C.resize(49)

In [ ]:
A+B

In [ ]:
A*B

In [ ]:
A+C

In [ ]:
B*C

### Questão 8

In [ ]:
np.arange(0,9).reshape(3,3)

### Questão 9

In [ ]:
np.random.rand(3,3,3)

### Questão 10

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
x = np.arange(0,4*np.pi,0.01)
y = np.sin(x)
plt.title("Grafico do Seno") 
plt.xlabel("Eixo x") 
plt.ylabel("Eixo y") 
plt.plot(x,y) 
plt.show()