Aluno: Arthur Mauricio

In [159]:
import numpy as np
import scipy.linalg as sla

In [160]:
def decomposicao_lu(a):
    m = len(a)

    ## Pivotando a matriz
    p = np.eye(m, dtype=np.double)

    for i in range(m):
        pivo = np.abs(a[i:, i]).argmax() + i
        if i != pivo:
            p[[i, pivo]] = p[[pivo, i]]

    # Escalonando
    l = np.eye(m, dtype=np.double)
    u = p @ a

    for i in range(m):
        for j in range(i + 1, m):
            mult = u[j, i] / u[i, i]
            l[j, i] = mult
            u[j] = u[j] - (mult * u[i])

    return p, l, u


def sist_lin_tri_sup(A, b):
    n = len(b)
    x = np.empty(n)
    x[-1] = b[-1] / A[-1, -1]
    for i in range(n - 2, -1, -1):
        x[i] = (b[i] - np.sum(A[i, i + 1:] * x[i + 1:])) / A[i, i]
    return x


def resolucao_lu(p, l, u, b):
    y = sla.solve_triangular(l, p@b, lower=True)
    x = sla.solve_triangular(u, y, lower=False)
    return np.array(x, dtype=float)

In [161]:
def analise_sistema(a,b):
    print("**Calculando resolução com a lib scipy:**")
    p,l,u = sla.lu(a)

    print("Recuperando a matriz a partir da expressão p * l * u:")
    print(p@l@u)
    print("\n")

    L_U, piv = sla.lu_factor(a)
    x = sla.lu_solve((L_U, piv), b)
    print("Conjunto solução do sistema:")
    print(x)
    solucao_correta = (a @ x == b).all()
    print("Solução validada!" if solucao_correta else "Conjunto solução não resolve o sistema :(")
    print("\n")


    print("**Calculando resolução com minha implementação:**")
    pm,lm,um = decomposicao_lu(a)

    print("Recuperando a matriz a partir da expressão p * l * u")
    print(pm@lm@um)
    print("\n")

    xm = resolucao_lu(pm,lm,um,b)
    print("Conjunto solução do sistema:")
    print(x)
    solucao_correta = (a @ xm == b).all()
    print("Solução validada!" if solucao_correta else "Conjunto solução não resolve o sistema :(")
    print("\n")


## Questão a

In [162]:
a = np.array([[1,1,1],[4,4,2],[2,1,-1]],dtype=float)
b = np.array([1,2,0])

analise_sistema(a,b)

**Calculando resolução com a lib scipy:**
Recuperando a matriz a partir da expressão p * l * u:
[[ 1.  1.  1.]
 [ 4.  4.  2.]
 [ 2.  1. -1.]]


Conjunto solução do sistema:
[ 1. -1.  1.]
Solução validada!


**Calculando resolução com minha implementação:**
Recuperando a matriz a partir da expressão p * l * u
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]




/tmp/ipykernel_28613/1335313586.py:18: RuntimeWarning: divide by zero encountered in double_scalars
  mult = u[j, i] / u[i, i]
/tmp/ipykernel_28613/1335313586.py:20: RuntimeWarning: invalid value encountered in multiply
  u[j] = u[j] - (mult * u[i])
/tmp/ipykernel_28613/19113813.py:22: RuntimeWarning: invalid value encountered in matmul
  print(pm@lm@um)


ValueError: array must not contain infs or NaNs

NOTA: Tentei várias implementações com esse primeiro caso, e nenhuma funcionou bem... Acho que po ter dois 4 na segunda linha na hora que o código vai zerar um no escalonamento, acaba zerando tudo.

## Questão b

In [163]:
a = np.array([[7, -7, 1], [-3, 3, 2], [7, 7, -72]], dtype=float)
b = np.array([1, 2, 7], dtype=float)

analise_sistema(a,b)

**Calculando resolução com a lib scipy:**
Recuperando a matriz a partir da expressão p * l * u:
[[  7.  -7.   1.]
 [ -3.   3.   2.]
 [  7.   7. -72.]]


Conjunto solução do sistema:
[5.64285714 5.64285714 1.        ]
Solução validada!


**Calculando resolução com minha implementação:**
Recuperando a matriz a partir da expressão p * l * u
[[  7.  -7.   1.]
 [ -3.   3.   2.]
 [  7.   7. -72.]]


Conjunto solução do sistema:
[5.64285714 5.64285714 1.        ]
Solução validada!




## Questão b

In [164]:
a = np.array([[1,2,3,4],[2,2,3,4],[3,3,3,4],[4,4,4,4]], dtype=float)
b = np.array([20,22,22,24], dtype=float)
analise_sistema(a,b)

**Calculando resolução com a lib scipy:**
Recuperando a matriz a partir da expressão p * l * u:
[[1. 2. 3. 4.]
 [2. 2. 3. 4.]
 [3. 3. 3. 4.]
 [4. 4. 4. 4.]]


Conjunto solução do sistema:
[ 2. -2.  2.  4.]
Solução validada!


**Calculando resolução com minha implementação:**
Recuperando a matriz a partir da expressão p * l * u
[[3. 3. 3. 4.]
 [4. 4. 4. 4.]
 [1. 2. 3. 4.]
 [2. 2. 3. 4.]]


Conjunto solução do sistema:
[ 2. -2.  2.  4.]
Solução validada!


