In [323]:
import numpy as np
import scipy.linalg as sla

Aluno: Arthur Mauricio Thomaz

In [324]:
def res_gaussiana_pivot(A: np.ndarray,B:np.ndarray):

    def sist_lin_tri_sup(A, b):
        n = len(b)
        x = np.empty(n)
        x[-1] = b[-1] / A[-1, -1]
        for i in range(n - 2, -1, -1):
            x[i] = (b[i] - np.sum(A[i, i + 1:] * x[i + 1:])) / A[i, i]
        return x

    def linha_com_maior_pivo(_a_b, l, c):
        mod_pivos = np.abs(_a_b[l:, c + 1])
        pivo_idx = mod_pivos.argmax()
        return pivo_idx + 1

    def escalona(_a_b):
        n = len(A)
        for c in range(n-1):
            for l in range(c+1,n):
                _a_b[l] = _a_b[l] - (_a_b[l,c]/_a_b[c,c])*_a_b[c]
        return _a_b[:,:-1], _a_b[:,-1]


    def swap_linhas(_a_b, l_1, l_2):
        _a_b[[l_1, l_2]] = _a_b[[l_2, l_1]]

    ## Calculando melhores pivvos locais

    A_B = np.c_[A,B]
    co = np.copy(A_B)
    for col in range(A_B.shape[0] - 1):
        idx_pivo_c = linha_com_maior_pivo(A_B, col, col)
        if col != idx_pivo_c:
            swap_linhas(A_B, col, idx_pivo_c)
    # swap_linhas(A_B, 1, 0)

    print("Matriz reorganizada:")
    print(A_B)

    # Calculando a matriz escalonada
    A_e, B_e = escalona(A_B)
    print("Matriz escalonada:")
    print(np.c_[A_e, B_e])

    # Calculando o resultado a partir da matriz triangular superior
    return sist_lin_tri_sup(A_e, B_e)

### Letra A

In [325]:
A = np.array([[1,1,1], [4,4,2],[2,1,-1]])
B = np.array([1,2,0])

In [326]:
np.c_[A,B]

array([[ 1,  1,  1,  1],
       [ 4,  4,  2,  2],
       [ 2,  1, -1,  0]])

In [327]:
resultado_a = res_gaussiana_pivot(A,B)
resultado_a

Matriz reorganizada:
[[ 2  1 -1  0]
 [ 4  4  2  2]
 [ 1  1  1  1]]
Matriz escalonada:
[[ 2  1 -1  0]
 [ 0  2  4  2]
 [ 0  0  1  1]]


array([ 1., -1.,  1.])

Comparando com o resultado da biblioteca scipy:

In [328]:
sla.solve(A,B)

array([ 1., -1.,  1.])

In [329]:
resultado_a == sla.solve(A,B)

array([ True,  True,  True])

### Letra B

In [330]:
A = np.array([[7,-7,1],[-3,3,2],[7,7,-72]])
B = np.array([1,2,7])

In [331]:
np.c_[A,B]

array([[  7,  -7,   1,   1],
       [ -3,   3,   2,   2],
       [  7,   7, -72,   7]])

In [332]:
resultado_b = res_gaussiana_pivot(A,B)
resultado_b

Matriz reorganizada:
[[ -3   3   2   2]
 [  7   7 -72   7]
 [  7  -7   1   1]]
Matriz escalonada:
[[ -3   3   2   2]
 [  0  14 -67  11]
 [  0   0   5   5]]


array([5.57142857, 5.57142857, 1.        ])

Comparando com o resultado da biblioteca scipy:

In [333]:
sla.solve(A,B)

array([5.64285714, 5.64285714, 1.        ])

In [334]:
sla.solve(A,B) == resultado_b

array([False, False,  True])

Houve uma diferença minima nos valores do resultado, mas vamos considerar uma apromixação consideravel do resultado da biblioteca.

### Letra C

In [335]:
A = np.array([[1,2,3,4],[2,2,3,4],[3,3,3,4],[4,4,4,4]])
B = np.array([20,22,22,24])

In [336]:
np.c_[A,B]

array([[ 1,  2,  3,  4, 20],
       [ 2,  2,  3,  4, 22],
       [ 3,  3,  3,  4, 22],
       [ 4,  4,  4,  4, 24]])

In [337]:
resultado_c = res_gaussiana_pivot(A,B)
resultado_c

IndexError: index 4 is out of bounds for axis 0 with size 4