Aluno: Arthur Mauricio

In [1]:
import numpy as np
from enum import Enum
import scipy.linalg as sla

## 1.1

a)

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 1, 1])
np.linalg.matrix_rank(a)

2

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.c_[a, b]

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [7, 8, 9, 1]])

In [5]:
np.linalg.matrix_rank(np.c_[a, b])

2

rank(ã) == rank(a) < n, portanto é um sistema possível e indeterminado

b)

In [6]:
a = np.array([[2, 3], [-4, -6]])
b = np.array([10, -10])
np.linalg.matrix_rank(a)

1

In [7]:
np.linalg.matrix_rank(np.c_[a, b])

2

rank(ã) > rank(a) , portanto é um sistema impossível

## 1.2

In [8]:
a = np.array([[3, 4, -5, 1], [0, 1, 1, -2], [0, 0, 4, -5], [0, 0, 0, 2]])
b = np.array([-10, -1, 3, 2])

In [9]:
a

array([[ 3,  4, -5,  1],
       [ 0,  1,  1, -2],
       [ 0,  0,  4, -5],
       [ 0,  0,  0,  2]])

Criando um vetor cheio de zeros

In [10]:
n = np.empty(len(b))

Calculando a icognita de maior indice

In [11]:
n[-1] = b[-1] / a[-1][-1]

In [12]:
for i in range(len(b) - 2, -1, -1):
    n[i] = (b[i] - np.sum(a[i, i + 1:] * n[i + 1:])) / a[i, i]

In [13]:
n

array([ 1., -1.,  2.,  1.])

In [14]:
def sist_lin_tri_sup(A, b):
    n = len(b)
    x = np.empty(n)
    x[-1] = b[-1] / A[-1, -1]
    for i in range(n - 2, -1, -1):
        x[i] = (b[i] - np.sum(A[i, i + 1:] * x[i + 1:])) / A[i, i]
    return x

In [15]:
sist_lin_tri_sup(a, b)

array([ 1., -1.,  2.,  1.])

## 1.3

In [16]:
a = np.array([[3, 0, 0, 0], [2, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1]])
b = np.array([4, 2, 4, 2])

In [17]:
a

array([[3, 0, 0, 0],
       [2, 1, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 1, 1]])

In [18]:
x = np.empty(len(b))
x[0] = b[0] / a[0, 0]
x

array([1.33333333e+000,             nan, 1.48219694e-323, 9.88131292e-324])

In [19]:
for i in range(1, len(b)):
    x[i] = (b[i] - np.sum(a[i, :i] * x[:i])) / a[i, i]

In [20]:
x

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])

## 1.4

In [21]:
class Tipos_Matriz(Enum):
    MATRIZ = 0
    TRIANGULAR_SUP = 1
    TRIANGULAR_INF = 2


switch_case = {
    Tipos_Matriz.TRIANGULAR_SUP: lambda a, b: sla.solve_triangular(a, b, lower=False),
    Tipos_Matriz.TRIANGULAR_INF: lambda a, b: sla.solve_triangular(a, b, lower=True),
    Tipos_Matriz.MATRIZ: lambda a, b: b / a.diagonal()
}


def solucoes_triviais(a, b):
    rank_a = np.linalg.matrix_rank(a)
    rank_at = np.linalg.matrix_rank(np.c_[a, b])
    tamanho = a.shape[1]
    if rank_at > rank_a and rank_a < tamanho:
        raise Exception("Não existe solução precisa")
    else:
        soma_sup = sum([a[j][i] for j in range(a.shape[1]) for i in range(a.shape[1])])
        soma_inf = sum([a[i][j] for j in range(a.shape[1]) for i in range(a.shape[1])])

        if soma_sup == 0:
            tipo = Tipos_Matriz.TRIANGULAR_INF
        elif soma_inf == 0:
            tipo = Tipos_Matriz.TRIANGULAR_SUP
        else:
            tipo = Tipos_Matriz.MATRIZ

        return switch_case[tipo](a, b)

Testando matriz diagonal:

In [22]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 1, 1])
solucoes_triviais(a,b)

array([1.        , 0.2       , 0.11111111])

Testando matriz triangular superior:

In [23]:
a = np.array([[3, 4, -5, 1], [0, 1, 1, -2], [0, 0, 4, -5], [0, 0, 0, 2]])
b = np.array([-10, -1, 3, 2])
solucoes_triviais(a,b)

array([-3.33333333, -1.        ,  0.75      ,  1.        ])

Testando matriz triangular inferior:

In [24]:
a = np.array([[3, 0, 0, 0], [2, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1]])
b = np.array([4, 2, 4, 2])
solucoes_triviais(a,b)

array([1.33333333, 2.        , 4.        , 2.        ])