In [109]:
import numpy as np
import scipy.linalg as sla

Aluno: Arthur Mauricio Thomaz Soares

## Decomposição LU

In [110]:
def decomposicao_lu(a):
    m = len(a)

    p = np.eye(m, dtype=np.double)
    l = np.eye(m, dtype=np.double)
    u = np.array(a, dtype=float)

    for i in range(m):
        pivo = np.abs(u[i:, i]).argmax() + i
        if i != pivo:
            p[[i, pivo]] = p[[pivo, i]]
            u[[i, pivo]] = u[[pivo, i]]
        for j in range(i + 1, m):
            mult = u[j, i] / u[i, i]
            l[j, i] = mult
            u[j] = u[j] - (mult * u[i])

    return p, l, u


def sist_lin_tri_sup(A, b):
    n = len(b)
    x = np.empty(n)
    x[-1] = b[-1] / A[-1, -1]
    for i in range(n - 2, -1, -1):
        x[i] = (b[i] - np.sum(A[i, i + 1:] * x[i + 1:])) / A[i, i]
    return x


def resolucao_lu(p, l, u, b):
    y = sla.solve_triangular(l, p@b, lower=True)
    x = sla.solve_triangular(u, y, lower=False)
    return x



In [111]:
# a = np.array([[1, 1, 1], [2, 1, -1], [2, -1, 1]], dtype=float)
# b = np.array([-2, 1, 3], dtype=float)
a = np.array([[1, 1, 1], [4, 4, 2], [2, 1, -1]], dtype=float)
b = np.array([1, 2, 0], dtype=float)

In [112]:
p, l, u = sla.lu(a)
LU, piv = sla.lu_factor(a)
x = sla.lu_solve((LU, piv), b)
x

array([ 1., -1.,  1.])

In [118]:
p@b

array([2., 0., 1.])

In [113]:
x = resolucao_lu(p, l, u, b)
x

array([ 7., -9.,  4.])

In [114]:
p, l, u = decomposicao_lu(a)
x = resolucao_lu(p, l, u, b)
x

array([0. , 0.5, 0. ])

In [115]:
p

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [116]:
a @ x

array([0.5, 2. , 0.5])