In [423]:
import numpy as np
import scipy.linalg as sla

Aluno: Arthur Mauricio Thomaz Soares

## Decomposição LU

In [424]:
def decomposicao_lu(a):
    p = np.identity(len(a))
    l = np.identity(len(a))
    u = np.array(a, dtype=float)
    m = len(u)

    for i in range(m):
        pivo = np.abs(u[i:, i]).argmax() + i
        if i != pivo:
            u[[i, pivo]] = u[[pivo, i]]
            p[[i, pivo]] = p[[pivo, i]]
        for j in range(i + 1, m):
            mult = u[j, i] / u[i, i]
            l[j, i] = mult
            u[j] = u[j] - (mult * u[i])

    return p, l, u


def sist_lin_tri_sup(A, b):
    n = len(b)
    x = np.empty(n)
    x[-1] = b[-1] / A[-1, -1]
    for i in range(n - 2, -1, -1):
        x[i] = (b[i] - np.sum(A[i, i + 1:] * x[i + 1:])) / A[i, i]
    return x


def resolucao_lu(p, l, u, b):
    y = sla.solve_triangular(l, b@p, lower=True)
    x = sla.solve_triangular(u, y, lower=False)
    return x



In [425]:
# a = np.array([[1, 1, 1], [2, 1, -1], [2, -1, 1]], dtype=float)
# b = np.array([-2, 1, 3], dtype=float)
a = np.array([[1,1,1],[4,4,2],[2,1,-1]], dtype=float)
b = np.array([1,2,0], dtype=float)

In [426]:
p, l, u = sla.lu(a)
mp, ml, mu = decomposicao_lu(a)

In [427]:
LU, piv = sla.lu_factor(a)
x = sla.lu_solve((LU, piv), b)
x

array([ 1., -1.,  1.])

In [428]:
a @ x

array([1., 2., 0.])

In [429]:
x = resolucao_lu(mp, ml, mu, b)
x

array([ 7., -9.,  4.])

In [430]:
a @ x

array([2., 0., 1.])