# <center>__MÉTODOS NUMÉRICOS__</center>
## <center>__Tutorial Básico de Numpy__</center>

Nesse ponto, é esperado que você tenha feito a instalação do anaconda 3 em sua máquina e passado pelo tutorial de Jupyter Notebook. Se não o fez, retorne e faça, ou não terá sucesso nesse tutorial.

A ideia aqui é servir de auto estudo. Dessa forma, espera-se que você crie um notebook novo e execute todos os comandos as seguir, tentando entender cada saída, e responda a todos os exercícios espalhados no próprio notebook que você acabou de criar, anotando suas dúvidas, quando tiver (após consultar as referências da biblioteca, lógico), para que que essas sejam discutidas em sala de aula. De outro jeito, não haverá aprendizado

Começamos, como discutido em sala, pela importação do módulo, 

In [13]:
import numpy as np

In [14]:
lista = [-2, 4., '7', 9]
lista

[-2, 4.0, '7', 9]

In [15]:
lista*2

[-2, 4.0, '7', 9, -2, 4.0, '7', 9]

In [16]:
b = []
for i in lista: b.append(i*2)
b

[-4, 8.0, '77', 18]

<div class="alert alert-block alert-info">
1. CRIANDO ARRAYS
</div>

Existem várias formas de criar arrays, pode ser através do método np.array(), usando uma lista ou tupla do python:

string > complex > float > int

In [17]:
np.array((1,2))

array([1, 2])

In [18]:
np.array([-2, 4., 7, 9j])

array([-2.+0.j,  4.+0.j,  7.+0.j,  0.+9.j])

In [19]:
0.1 + 1j

(0.1+1j)

In [20]:
my_tuple = (8, -5, 0, 3.2)
arr = np.array(my_tuple)

print('arr = ', arr)

arr =  [ 8.  -5.   0.   3.2]


Usando o método arange (similar ao range do python): 

In [21]:
np.arange(12) # vetor de 0 a 12, com passo 1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
np.arange(2,12) #vetor de 2 a 12, com passo unitário

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
np.arange(2,12,2) #vetor de 2 a 12, com passo 2

array([ 2,  4,  6,  8, 10])


Temos também outro método, o linspace

In [24]:
np.linspace(10) # não roda só com um valor

TypeError: _linspace_dispatcher() missing 1 required positional argument: 'stop'

In [ ]:
np.linspace(1,10) #vetor entre 1 e 10 com 50 valores

In [ ]:
np.linspace(1,10,10) #vetor entre 1 e 10 com 10 valores

#### Outros métodos

In [ ]:
np.empty(5) # normalmente a saída é lixo de memória ou zeros

In [ ]:
np.empty((2,3))

In [ ]:
# Np.Eye

np.eye(4) # eye cria uma array de duas dimensões com 1 na da diagnoal e 0 nos outros elementos 

In [ ]:
10*np.eye(4)

Usando os métodos 'zeros()' e 'ones()' para criar arrays de 0 e 1, respectivamente:

In [ ]:
arr = np.zeros(8) # array contendo 8 'zeros'
print (arr)

arr2 = np.ones((4,3)) # array contendo 12 'uns', no formato 4 x 3
print(arr2)

<div class="alert alert-block alert-info">
2. ATRIBUTOS DAS ARRAYS
</div>

Existem vários atributos, mas o três principais são .shape , .size e .dtype

In [ ]:
arr = np.linspace(.5, 50, 12)
arr

In [ ]:
m = arr.reshape(3,4)
m

In [ ]:
print('.shape: ', arr.shape)    # imprime o formato da array
print('.size: ', arr.size)      # imprime o tamanho da array
print('.dtype: ', arr.dtype)    # imprime o tipo de dado dos elementos

In [ ]:
print('.shape: ', m.shape)    # imprime o formato da array
print('.size: ', m.size)      # imprime o tamanho da array
print('.dtype: ', m.dtype)    # imprime o tipo de dado dos elementos

Outros atributos:

In [ ]:
print('.ndim: ', m.ndim)          # número de dimensões
print('.itemsize: ', m.itemsize)      # tamanho de cada elemento em bytes

<div class="alert alert-block alert-info">
3. MÉTODOS
</div>

Existem inúmeros métodos que nos ajudam a trabalhar com numpy arrays, vou mostrar os mais usados:

In [ ]:
arr = np.arange(1,10)
print('array original: ', arr, '\n')

Como já vimos 'reshape()' muda o formato da array, MAS o número de elementos dos dois formatos tem que coincidir, exemplo:

In [ ]:
arr2 = arr.reshape((3,3))
print ('formato 3x3: \n' , arr2, '\n')

In [ ]:
arr2.reshape(9)

In [ ]:
arr.max() # retorna o valor máximo

In [ ]:
print(arr.argmax()) # retorna o índice que contém o valor máximo
arr[8] == arr[arr.argmax()]

In [ ]:
arr.min() # retorna o mínimo

In [ ]:
print(arr.argmin()) # retorna o índice que contém o valor máximo
arr[0] == arr[arr.argmin()]

In [ ]:
arr.mean() # retorna a média

In [ ]:
arr.std() # retorna o desvio padrão

In [ ]:
arr.sum() #retorna a soma de todos os elementos da array

<div class="alert alert-block alert-info">
4. OPERAÇÕES BÁSICAS
</div>

É bem fácil realizar operações matemáticas com arrays 

In [ ]:
# vamos criar as arrays A e B para fazer operações com elas

A = np.arange(10)
B = np.arange(10,38,3)
C = np.array([0., 1., 2., 3., 4., 5., 6., 7.,np.nan, np.nan])

print (' A: ', A, '\n', 'B: ', B, '\n', 'C: ', C)

In [ ]:
A+B


In [ ]:
A**2

####  Perceba que se você dividir por zero, numpy não vai dar erro (o código vai rodar), porém vai emitir uma advertência!

In [ ]:
B/A

In [ ]:
10/0

BROADCAST = transmissão

In [ ]:
''' Você pode fazer operações envolvendo arrays e um único elemento, dessa forma numpy itera a operação 
do elemento único com todos os componentes da array, exemplo: ''' 

A+C

<div class="alert alert-block alert-info">
5. FUNÇÕES UNIVERSAIS
</div>

In [ ]:
arr

In [ ]:
np.sqrt(arr) # retorna um array com a raiz quadrada de cada elemento

In [ ]:
np.sin(arr) # retorna um array com o seno de cada elemento

In [ ]:
np.cos(arr) # retorna um array com o cosseno de cada elemento

In [ ]:
np.exp(arr) # retorna um array com o exponencial cada elemento (e^x)

<div class="alert alert-block alert-info">
6. INDEXAÇÃO E FATIAMENTO (SLICING)
</div>

O acesso de elementos de uma array, funciona de forma similar ao das listas do Python:

In [ ]:
# criar uma array com o quadrado dos números de 1 a 10
arr = np.arange(1, 10) **2
arr

In [ ]:
# acessando o primeiro elemento
print('1º elemento: ', arr[0])    # lembrar que índice começa do 0

# acessando o quinto elemento
print ('5º elemento: ', arr[4])   # O quinto elemento é acessado pelo índice 4

In [ ]:
# Em um array de duas dimensões (ou mais) existem duas formas de acessar o índice:

arr = arr.reshape((3,3))
print (arr, '\n')



# acessando o último elemento usando o -1
arr[:,1:] 

In [ ]:
arr

In [ ]:
# Para acessar fatias de elementos, usamos o slice [i:i], exemplo

# linha: acessar da linha de índice 0 a linha de índice 2 (excluindo esta) = [0:2]
# coluna: acessar da coluna de índice 0 a coluna de 3 (excluindo esta) = [0:3] - no nosso caso, todas as colunas
print(arr[0:2 , 0:3],'\n')

# outra forma de obter o mesmo resultado é usando [:], que pega todos os elementos
print(arr[0:2 , :])

In [ ]:
# Podemos criar uma nova array com slice de outra

arr2 = arr[ : , 1:3]
arr2

In [ ]:
# Podemor atribuir novos elementos a nossa array, usando slice

arr[1:2, :] = -99
arr

## Uma imagem vale mais que mil palavras:

![Image of Yaktocat](http://www.scipy-lectures.org/_images/numpy_indexing.png)

#### SELEÇÃO CONDICIONAL

Uma forma interessante de selecionar elementos baseado em alguma condição

In [ ]:
A = np.arange(10)
print ('A: ', A)

In [ ]:
A > 5 # retorna uma array de variáveis booleanas de acordo com a condição

In [ ]:
# Também odemos criar uma array a partir dessa condição
B = A > 5

In [ ]:
# Isso nos dá 2 opções para fazer seleção condicional, passando a condição ou passando o array como índice  

print (A [A > 5])

print (A [B])

# em ambos os casos só retorna os valores que admitem essa condição 